# Generated by Django 6.0 on 2026-01-28 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_hospital_alter_user_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='patient_unique_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
