# Generated by Django 6.0.1 on 2026-02-01 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_patient_city_patient_patient_unique_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='education',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='doctor',
            name='experience',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='nid',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='signature',
            field=models.TextField(blank=True, null=True),
        ),
    ]
