# Generated by Django 6.0 on 2026-02-08 15:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_seed_hospitals'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='doctor_unique_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doctors', to='authentication.hospital'),
        ),
        migrations.AddField(
            model_name='patient',
            name='consent_signed',
            field=models.BooleanField(default=False),
        ),
    ]
