# Generated by Django 6.0 on 2026-02-08 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_doctor_doctor_unique_id_doctor_hospital_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='nmic_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
