# Generated by Django 6.0.2 on 2026-02-13 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_doctorprofile_available_days_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorprofile',
            name='doctor_unique_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
