# Generated by Django 6.0.2 on 2026-02-13 09:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0010_doctorhospitalconnection_doctorschedule'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time_slot', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending Verification'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('consultation_type', models.CharField(choices=[('online', 'Video Consultation'), ('offline', 'In-Person Visit')], default='online', max_length=10)),
                ('payment_screenshot', models.ImageField(blank=True, null=True, upload_to='appointment_payments/')),
                ('symptoms', models.TextField(blank=True)),
                ('meeting_link', models.URLField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='authentication.doctorprofile')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='authentication.hospital')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='authentication.patientprofile')),
            ],
            options={
                'ordering': ['-date', '-time_slot'],
            },
        ),
    ]
