# Generated by Django 6.0.2 on 2026-02-13 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0011_appointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='booking_reference',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
