# Generated by Django 6.0.2 on 2026-02-15 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0014_doctorschedule_day_of_week_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='is_emergency',
            field=models.BooleanField(default=False),
        ),
    ]
