# Generated by Django 6.0.2 on 2026-02-15 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0016_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorprofile',
            name='signature_image',
            field=models.ImageField(blank=True, null=True, upload_to='doctor_signatures/'),
        ),
    ]
