# Generated by Django 6.0.2 on 2026-02-15 21:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0017_doctorprofile_signature_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medicalreport',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='medicalreport',
            name='report_type',
            field=models.CharField(choices=[('consultation', 'Consultation Report'), ('lab_report', 'Lab/Test Report')], default='consultation', max_length=20),
        ),
        migrations.AddField(
            model_name='medicalreport',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_reports', to=settings.AUTH_USER_MODEL),
        ),
    ]
