import React, { useState } from 'react';
import { Card } from '../ui/Card';
import { Button } from '../ui/Button';
import { SignatureCanvas } from './SignatureCanvas';
import { FileUp, PenLine, Image as ImageIcon, Trash2 } from 'lucide-react';

interface SignatureManagerProps {
    onSave: (signature: string) => void;
    initialSignature?: string;
}

export const SignatureManager: React.FC<SignatureManagerProps> = ({ onSave, initialSignature }) => {
    const [mode, setMode] = useState<'draw' | 'upload'>('draw');
    const [preview, setPreview] = useState<string | null>(initialSignature || null);

    const handleFileUpload = (e: React.ChangeEvent<HTMLInputElement>) => {
        const file = e.target.files?.[0];
        if (file) {
            const reader = new FileReader();
            reader.onloadend = () => {
                const base64String = reader.result as string;
                setPreview(base64String);
                onSave(base64String);
            };
            reader.readAsDataURL(file);
        }
    };

    const handleClear = () => {
        setPreview(null);
        onSave('');
    };

    return (
        <Card className="p-6 border-2 border-dashed border-gray-200 bg-gray-50/50">
            <div className="flex space-x-2 mb-6 p-1 bg-white rounded-xl shadow-sm border border-gray-100">
                <Button
                    variant={mode === 'draw' ? 'primary' : 'ghost'}
                    onClick={() => setMode('draw')}
                    className="flex-1 rounded-lg"
                    size="sm"
                >
                    <PenLine size={16} className="mr-2" />
                    Draw Digital
                </Button>
                <Button
                    variant={mode === 'upload' ? 'primary' : 'ghost'}
                    onClick={() => setMode('upload')}
                    className="flex-1 rounded-lg"
                    size="sm"
                >
                    <FileUp size={16} className="mr-2" />
                    Upload Copy
                </Button>
            </div>

            {mode === 'draw' ? (
                <div className="space-y-4">
                    <SignatureCanvas onSave={(sig) => { setPreview(sig); onSave(sig); }} />
                    {preview && mode === 'draw' && (
                        <div className="p-4 bg-white rounded-xl border border-blue-100 flex justify-center">
                            <img src={preview} alt="Preview" className="h-16 object-contain" />
                        </div>
                    )}
                </div>
            ) : (
                <div className="space-y-4">
                    {!preview ? (
                        <label className="flex flex-col items-center justify-center h-48 bg-white rounded-2xl border-2 border-dashed border-gray-300 cursor-pointer hover:border-blue-500 hover:bg-blue-50 transition-all">
                            <ImageIcon size={48} className="text-gray-400 mb-2" />
                            <span className="text-sm font-medium text-gray-600">Click to upload signature image</span>
                            <span className="text-xs text-gray-400 mt-1">PNG, JPG up to 2MB</span>
                            <input type="file" className="hidden" accept="image/*" onChange={handleFileUpload} />
                        </label>
                    ) : (
                        <div className="relative group p-4 bg-white rounded-2xl border border-gray-200">
                            <img src={preview} alt="Uploaded Signature" className="h-32 w-full object-contain" />
                            <button
                                onClick={handleClear}
                                className="absolute top-2 right-2 p-2 bg-red-50 text-red-600 rounded-full opacity-0 group-hover:opacity-100 transition-opacity"
                            >
                                <Trash2 size={18} />
                            </button>
                        </div>
                    )}
                </div>
            )}

            <p className="mt-4 text-[10px] text-gray-400 text-center italic">
                This signature will be used for all digital prescriptions generated by you.
            </p>
        </Card>
    );
};
