steps:
  # Build backend
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/medisewa-backend', 'backend/']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/medisewa-backend']
    
  # Build CHATBOT (NEW)
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/medisewa-chatbot', 'backend/chatbot/']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/medisewa-chatbot']
    
  # Deploy backend
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'medisewa-backend'
      - '--image'
      - 'gcr.io/$PROJECT_ID/medisewa-backend'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
    
  # Deploy CHATBOT (NEW)
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'medisewa-chatbot'
      - '--image'
      - 'gcr.io/$PROJECT_ID/medisewa-chatbot'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--set-env-vars'
      - 'GOOGLE_API_KEY=${_GOOGLE_API_KEY}'

images:
  - 'gcr.io/$PROJECT_ID/medisewa-backend'
  - 'gcr.io/$PROJECT_ID/medisewa-chatbot'

substitutions:
  _GOOGLE_API_KEY: 'AIzaSyBom-5HsDAUqFTmkobNIw9j3_lDaP3-siU'  # Using existing key from file

timeout: '1200s'