# Generated by Django 6.0 on 2026-02-08 05:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
        ('authentication', '0005_doctor_latitude_doctor_longitude_hospital_latitude_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnosis', models.TextField()),
                ('symptoms', models.TextField()),
                ('prescription', models.TextField()),
                ('record_date', models.DateField(auto_now_add=True)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='medical_records/')),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentication.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_records', to='authentication.patient')),
            ],
        ),
    ]
