# Generated by Django 5.2.8 on 2026-02-12 14:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Hospital",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("location", models.CharField(max_length=300)),
                ("phone", models.CharField(blank=True, default="", max_length=20)),
                ("email", models.EmailField(blank=True, default="", max_length=254)),
                ("website", models.URLField(blank=True, default="")),
                ("address", models.TextField(blank=True, default="")),
                ("image", models.URLField(blank=True, default="")),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Doctor",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("specialties", models.CharField(max_length=200)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(blank=True, default="", max_length=20)),
                (
                    "rating",
                    models.DecimalField(decimal_places=1, default=4.5, max_digits=2),
                ),
                ("reviews_count", models.IntegerField(default=0)),
                ("experience_years", models.IntegerField(default=0)),
                (
                    "consultation_fee",
                    models.DecimalField(decimal_places=2, default=500, max_digits=10),
                ),
                ("image", models.URLField(blank=True, default="")),
                (
                    "availability_days",
                    models.CharField(default="Mon,Tue,Wed,Thu,Fri", max_length=100),
                ),
                (
                    "availability_start",
                    models.CharField(default="09:00 AM", max_length=20),
                ),
                (
                    "availability_end",
                    models.CharField(default="05:00 PM", max_length=20),
                ),
                ("time_slot_duration", models.IntegerField(default=30)),
                (
                    "zoom_meeting_id",
                    models.CharField(blank=True, default="", max_length=50),
                ),
                ("zoom_meeting_url", models.URLField(blank=True, default="")),
                ("zoom_join_url", models.URLField(blank=True, default="")),
                (
                    "zoom_password",
                    models.CharField(blank=True, default="", max_length=50),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "hospital",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="doctors",
                        to="appointments.hospital",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Appointment",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("specialty", models.CharField(max_length=100)),
                ("appointment_type", models.CharField(max_length=50)),
                ("date", models.DateField()),
                ("time", models.CharField(max_length=20)),
                ("full_name", models.CharField(max_length=200)),
                ("age", models.IntegerField()),
                ("gender", models.CharField(max_length=20)),
                ("address", models.TextField()),
                ("email", models.EmailField(default="", max_length=254)),
                ("phone", models.CharField(default="", max_length=20)),
                ("status", models.CharField(default="Upcoming", max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("payment_status", models.CharField(default="pending", max_length=20)),
                (
                    "payment_amount",
                    models.DecimalField(decimal_places=2, default=500, max_digits=10),
                ),
                (
                    "esewa_transaction_id",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "zoom_meeting_id",
                    models.CharField(blank=True, default="", max_length=50),
                ),
                ("zoom_meeting_url", models.URLField(blank=True, default="")),
                ("zoom_join_url", models.URLField(blank=True, default="")),
                ("receipt_pdf_url", models.URLField(blank=True, default="")),
                (
                    "receipt_pdf_path",
                    models.CharField(blank=True, default="", max_length=500),
                ),
                (
                    "doctor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="appointments",
                        to="appointments.doctor",
                    ),
                ),
                (
                    "hospital",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="appointments",
                        to="appointments.hospital",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MedicalRecord",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("Lab Result", "Lab Result"),
                            ("Prescription", "Prescription"),
                            ("Radiology", "Radiology (X-Ray/MRI)"),
                            ("Vaccination", "Vaccination"),
                            ("Discharge Summary", "Discharge Summary"),
                            ("Appointment Receipt", "Appointment Receipt"),
                        ],
                        max_length=50,
                    ),
                ),
                ("date", models.DateField()),
                ("hospital_name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "privacy",
                    models.CharField(
                        choices=[
                            ("Private", "Private (Only Me)"),
                            ("Shared", "Shared (Visible to Doctors)"),
                        ],
                        default="Private",
                        max_length=20,
                    ),
                ),
                ("file", models.FileField(blank=True, null=True, upload_to="records/")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "appointment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="medical_records",
                        to="appointments.appointment",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TimeSlot",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "day_of_week",
                    models.IntegerField(
                        choices=[
                            (0, "Monday"),
                            (1, "Tuesday"),
                            (2, "Wednesday"),
                            (3, "Thursday"),
                            (4, "Friday"),
                            (5, "Saturday"),
                            (6, "Sunday"),
                        ]
                    ),
                ),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                ("is_available", models.BooleanField(default=True)),
                (
                    "doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="time_slots",
                        to="appointments.doctor",
                    ),
                ),
            ],
        ),
    ]
