# Generated by Django 5.2.8 on 2026-02-12 17:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0002_alter_appointment_id_alter_doctor_id_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("full_name", models.CharField(max_length=200)),
                ("phone", models.CharField(blank=True, default="", max_length=20)),
                ("age", models.IntegerField(blank=True, null=True)),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Male", "Male"),
                            ("Female", "Female"),
                            ("Other", "Other"),
                        ],
                        default="",
                        max_length=20,
                    ),
                ),
                ("address", models.TextField(blank=True, default="")),
                ("profile_image", models.URLField(blank=True, default="")),
                ("two_factor_enabled", models.BooleanField(default=False)),
                ("data_sharing_enabled", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Receipt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("receipt_number", models.CharField(max_length=50, unique=True)),
                (
                    "receipt_type",
                    models.CharField(
                        choices=[
                            ("appointment", "Appointment"),
                            ("lab", "Lab Test"),
                            ("pharmacy", "Pharmacy"),
                            ("other", "Other"),
                        ],
                        default="appointment",
                        max_length=20,
                    ),
                ),
                ("patient_name", models.CharField(max_length=200)),
                (
                    "patient_email",
                    models.EmailField(blank=True, default="", max_length=254),
                ),
                (
                    "patient_phone",
                    models.CharField(blank=True, default="", max_length=20),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("esewa", "eSewa"),
                            ("khalti", "Khalti"),
                            ("cash", "Cash"),
                            ("card", "Credit/Debit Card"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "transaction_id",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("description", models.TextField(blank=True)),
                ("hospital_name", models.CharField(max_length=200)),
                (
                    "doctor_name",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                (
                    "pdf_file",
                    models.FileField(blank=True, null=True, upload_to="receipts/"),
                ),
                ("pdf_url", models.URLField(blank=True, default="")),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "appointment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="receipts",
                        to="appointments.appointment",
                    ),
                ),
            ],
        ),
    ]
