# Generated by Django 5.2.8 on 2026-02-12 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0003_userprofile_receipt"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="consultation_fee",
            field=models.DecimalField(decimal_places=2, default=500, max_digits=10),
        ),
        migrations.AddField(
            model_name="appointment",
            name="notes",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="appointment",
            name="payment_method",
            field=models.CharField(default="cash", max_length=20),
        ),
        migrations.AddField(
            model_name="receipt",
            name="appointment_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="receipt",
            name="appointment_time",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
        migrations.AddField(
            model_name="receipt",
            name="department",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="receipt",
            name="status",
            field=models.CharField(
                choices=[
                    ("paid", "Paid"),
                    ("pending", "Pending"),
                    ("refunded", "Refunded"),
                ],
                default="paid",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="receipt",
            name="visit_type",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
    ]
