# Generated by Django 5.2.8 on 2026-02-13 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "appointments",
            "0004_appointment_consultation_fee_appointment_notes_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="hospital",
            name="specialties",
            field=models.CharField(default="", max_length=500),
        ),
    ]
